In [1]:
import pandas as pd
from pathlib import Path
import numpy as np
import ta

In [7]:
df = pd.read_parquet("/home/dusoudeth/Documentos/github/monnaie-par-renforcement/data/07_model_output/analytical_base_table_with_predictions.parquet")
df

,date,open,high,low,close,volume,Actual,SP500,fng_value,DJIA,...,volatility,sma_7,sma_21,rsi,sp500_change,djia_change,day_of_week,month,action,state
0,2023-09-28,26355.812500,27259.500000,26327.322266,27021.546875,14079002707,0.055,4299.70,46.0,33666.34,...,932.177734,26472.254185,26384.739769,58.839116,0.589307,0.345958,3,9,1,"[0.14676053544868617, 0.5165889935547844, 0.10..."
1,2023-09-29,27024.841797,27225.937500,26721.763672,26911.720703,10396435377,0.055,4288.05,48.0,33507.50,...,504.173828,26519.704520,26432.647693,55.476519,-0.270949,-0.471807,4,9,1,"[0.3535851925301603, 0.5611806313006115, 0.155..."
2,2023-09-30,26911.689453,27091.794922,26888.968750,26967.916016,5331172801,0.055,4288.05,47.0,33507.50,...,202.826172,26575.208147,26483.706659,57.181505,0.000000,0.000000,5,9,0,"[0.4025807304577756, 0.5031498925797389, 0.313..."
3,2023-10-01,26967.396484,28047.238281,26965.093750,27983.750000,9503917434,0.055,4288.05,48.0,33507.50,...,1082.144531,26821.911551,26586.160156,69.254953,0.000000,0.000000,6,10,0,"[0.37667426871591475, 0.41056750950256155, 0.2..."
4,2023-10-02,27976.798828,28494.458984,27347.787109,27530.785156,19793041322,0.055,4288.39,50.0,33433.35,...,1146.671875,26997.955078,26698.928292,59.713584,0.007929,-0.221294,0,10,0,"[0.2561809589048981, 0.6893047584509082, 0.198..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,2025-03-20,86872.953125,87443.265625,83647.195312,84167.195312,29028988961,0.055,5662.89,37.0,41953.32,...,3796.070312,84101.072545,85091.215030,41.476504,-0.218491,-0.026951,3,3,0,"[0.8651121514459753, 1.0, 0.6939068951798247, ..."
540,2025-03-21,84164.539062,84782.273438,83171.070312,84043.242188,19030452299,0.055,5667.56,37.0,41985.35,...,1611.203125,84111.664062,85075.511905,45.631484,0.082467,0.076347,4,3,0,"[0.9157147837279772, 1.0, 0.5556080555630045, ..."
541,2025-03-22,84046.257812,84513.875000,83674.781250,83832.484375,9863214091,0.055,5667.56,37.0,41985.35,...,839.093750,84038.717634,84970.777158,46.195645,0.000000,0.000000,5,3,0,"[0.9352427800010688, 0.944911808924391, 0.7970..."
542,2025-03-23,83831.898438,86094.781250,83794.914062,86054.375000,12594615537,0.055,5667.56,37.0,41985.35,...,2299.867188,84535.101562,84580.587798,60.029150,0.000000,0.000000,6,3,0,"[0.8808615328624225, 0.9101459091847831, 0.316..."
543,2025-03-24,86070.929688,88758.726562,85541.195312,87498.914062,34582604933,0.055,5767.57,37.0,42583.32,...,3217.531250,85024.133929,84648.837426,66.878624,1.764604,1.424235,0,3,0,"[0.36721440981373943, 0.6776660596143653, 0.07..."

In [5]:
df = pd.read_parquet("/home/dusoudeth/Documentos/github/monnaie-par-renforcement/data/07_model_output/predictions.parquet")
df

,date,state,action,q_values
0,2023-09-28,"[0.14676053544868617, 0.5165889935547844, 0.10...",1,"[1.8343271017074585, 1.8464043140411377, 1.829..."
1,2023-09-29,"[0.3535851925301603, 0.5611806313006115, 0.155...",1,"[5.388909339904785, 5.520545482635498, 5.38729..."
2,2023-09-30,"[0.4025807304577756, 0.5031498925797389, 0.313...",0,"[1.256715178489685, 1.2493642568588257, 1.2517..."
3,2023-10-01,"[0.37667426871591475, 0.41056750950256155, 0.2...",0,"[1.256715178489685, 1.2493642568588257, 1.2517..."
4,2023-10-02,"[0.2561809589048981, 0.6893047584509082, 0.198...",0,"[1.256715178489685, 1.2493642568588257, 1.2517..."
...,...,...,...,...
539,2025-03-20,"[0.8651121514459753, 1.0, 0.6939068951798247, ...",0,"[1.256715178489685, 1.2493642568588257, 1.2517..."
540,2025-03-21,"[0.9157147837279772, 1.0, 0.5556080555630045, ...",0,"[1.256715178489685, 1.2493642568588257, 1.2517..."
541,2025-03-22,"[0.9352427800010688, 0.944911808924391, 0.7970...",0,"[1.256715178489685, 1.2493642568588257, 1.2517..."
542,2025-03-23,"[0.8808615328624225, 0.9101459091847831, 0.316...",0,"[1.256715178489685, 1.2493642568588257, 1.2517..."
543,2025-03-24,"[0.36721440981373943, 0.6776660596143653, 0.07...",0,"[1.256715178489685, 1.2493642568588257, 1.2517..."

In [8]:
df['action'].value_counts()

action
0    527
1     17
Name: count, dtype: int64

.