In [1]:
import pandas as pd
from pathlib import Path
import numpy as np
import ta

In [11]:
df = pd.read_parquet("/home/dusoudeth/Documentos/github/monnaie-par-renforcement/data/07_model_output/dqn/analytical_base_table_with_predictions.parquet")
df

,date,open,high,low,close,volume,Actual,SP500,fng_value,DJIA,...,volatility,sma_7,sma_21,rsi,sp500_change,djia_change,day_of_week,month,action,state
0,2023-10-05,27798.646484,28091.861328,27375.601562,27415.912109,11877253670,0.055,4258.19,48.0,33119.57,...,716.259766,27434.208147,26891.497024,61.309230,-0.130402,-0.030124,3,10,1,"[0.08731753784145409, 0.30735291919788627, 0.0..."
1,2023-10-06,27412.123047,28252.537109,27215.552734,27946.597656,13492391599,0.055,4308.50,50.0,33407.58,...,1036.984375,27582.047712,26955.206752,66.010613,1.181488,0.869607,4,10,1,"[0.2103711896017513, 0.3338834303082457, 0.092..."
2,2023-10-07,27946.781250,28028.091797,27870.423828,27968.839844,6553044316,0.055,4308.50,49.0,33407.58,...,157.667969,27725.036830,27021.900019,66.189521,0.000000,0.000000,5,10,1,"[0.23952187186096652, 0.29935711021316125, 0.1..."
3,2023-10-08,27971.677734,28102.169922,27740.662109,27935.089844,7916875290,0.055,4308.50,50.0,33407.58,...,361.507812,27718.085379,27088.609654,70.965796,0.000000,0.000000,6,10,1,"[0.2241084063365508, 0.2442737343377716, 0.174..."
4,2023-10-09,27934.472656,27989.470703,27302.562500,27583.677734,12007668568,0.055,4335.66,50.0,33604.65,...,686.908203,27725.641462,27128.104725,64.902073,0.630382,0.589896,0,10,1,"[0.2100392435720854, 0.5651514877396284, 0.162..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,2025-03-20,86872.953125,87443.265625,83647.195312,84167.195312,29028988961,0.055,5662.89,37.0,41953.32,...,3796.070312,84101.072545,85091.215030,41.476504,-0.218491,-0.026951,3,3,1,"[0.4046111900972831, 0.5633544503523839, 0.354..."
533,2025-03-21,84164.539062,84782.273438,83171.070312,84043.242188,19030452299,0.055,5667.56,37.0,41985.35,...,1611.203125,84111.664062,85075.511905,45.631484,0.082467,0.076347,4,3,1,"[0.4387476374840095, 0.4567014865612286, 0.088..."
534,2025-03-22,84046.257812,84513.875000,83674.781250,83832.484375,9863214091,0.055,5667.56,37.0,41985.35,...,839.093750,84038.717634,84970.777158,46.195645,0.000000,0.000000,5,3,1,"[0.4207361039948152, 0.5373773782095437, 0.389..."
535,2025-03-23,83831.898438,86094.781250,83794.914062,86054.375000,12594615537,0.055,5667.56,37.0,41985.35,...,2299.867188,84535.101562,84580.587798,60.029150,0.000000,0.000000,6,3,1,"[0.5109893046313796, 1.0, 0.45691271330507927,..."
536,2025-03-24,86070.929688,88758.726562,85541.195312,87498.914062,34582604933,0.055,5767.57,37.0,42583.32,...,3217.531250,85024.133929,84648.837426,66.878624,1.764604,1.424235,0,3,1,"[0.9898161733733959, 1.0, 0.4749686718991323, ..."

In [9]:
df = pd.read_parquet("/home/dusoudeth/Documentos/github/monnaie-par-renforcement/data/07_model_output/dqn/predictions.parquet")
df

,date,state,action,q_values
0,2023-10-05,"[0.08731753784145409, 0.30735291919788627, 0.0...",1,"[-1868747.75, 477.1151428222656, -81966.6796875]"
1,2023-10-06,"[0.2103711896017513, 0.3338834303082457, 0.092...",1,"[-1894011.0, 473.9018859863281, -82810.671875]"
2,2023-10-07,"[0.23952187186096652, 0.29935711021316125, 0.1...",1,"[-1988680.125, 564.6466064453125, -88713.9375]"
3,2023-10-08,"[0.2241084063365508, 0.2442737343377716, 0.174...",1,"[-1951546.375, 538.9343872070312, -86659.640625]"
4,2023-10-09,"[0.2100392435720854, 0.5651514877396284, 0.162...",1,"[-1955432.25, 479.2527160644531, -85234.1796875]"
...,...,...,...,...
532,2025-03-20,"[0.4046111900972831, 0.5633544503523839, 0.354...",1,"[-12761949.0, 2060.90673828125, -528333.625]"
533,2025-03-21,"[0.4387476374840095, 0.4567014865612286, 0.088...",1,"[-12706296.0, 1879.397705078125, -521367.3125]"
534,2025-03-22,"[0.4207361039948152, 0.5373773782095437, 0.389...",1,"[-12068181.0, 1757.848876953125, -494511.875]"
535,2025-03-23,"[0.5109893046313796, 1.0, 0.45691271330507927,...",1,"[-11678828.0, 1416.104248046875, -471073.125]"
536,2025-03-24,"[0.9898161733733959, 1.0, 0.4749686718991323, ...",1,"[-13196252.0, 1784.68701171875, -537137.5625]"

In [10]:
df['action'].value_counts()

action
1    537
Name: count, dtype: int64

.